### PR TITLE
Adding hashtags to notes and displaying relevant lists

### PR DESCRIPTION
**Pull request by tannerdolby**
Hey! @binyamin 

I saw your last message in #33 and decided to make a new branch and a fresh PR for you to review. I hope your doing well and I'll plan on chatting with you soon.

This PR does successfully create and display hashtag permalinks with lists of relevant note lists, but the problem of dynamically displaying and grabbing the hashtags without the user supplying the hashtags to pagination data still needs to be sorted out.

### CODE REVIEW

**Comment by binyamin** [comment]
Can you remind me how we're differentiation wikilinks and tags?

**Comment by tannerdolby** [comment]
Yeah, in terms of style, the wikilinks are:`mediawiki-style, internal - [[ bar.md | example b ]]` 

Where the hashtags are `hashtag-style, internal - #tag - [#food](/notes/food/)`

Also, in the Eleventy config file, we're using two separate `.use()` statements to recognize wikilinks and tags.

> Some notes have the same filename as tags so thats why /tags/tag is currently being used in pagination permalinks to side step this

Other than that, the wikilinks provide a link to `/notes/art` where the hashtags are `/notes/tags/art` until the quote above is handled.

**Comment by binyamin** [comment]
@tannerdolby After careful procrastination — and laziness — I think that I'm going to wait for a dynamic solution. Thank you again for the PR.

**Comment by tannerdolby** [comment]
@binyamin Your welcome. Best of luck. Cya around

**Pull request closed without merging**
